package cli

import "strings"

// initCIChoice is what `buidl init` decided about GitHub Actions.
//
// The happy path is questions on a TTY. Flags answer the same questions
// without a prompt, so scripts never have to edit YAML.
type initCIChoice struct {
	CI      bool
	Staging bool
	Preview bool
}

// renderGithubWorkflow is the pipeline `buidl init` writes.
//
//   - CI only: deploy the single app on every push to main.
//   - + staging: push to main deploys staging; production is a promote.
//   - + review apps: each PR gets a preview, torn down when the PR closes.
func renderGithubWorkflow(staging, preview bool) string {
	var b strings.Builder
	b.WriteString("# Generated by `buidl init`.\n")
	b.WriteString("name: deploy\n\n")
	b.WriteString("on:\n")
	b.WriteString("  push:\n")
	b.WriteString("    branches: [main]\n")
	if preview {
		b.WriteString("  pull_request:\n")
		b.WriteString("    # closed is not in GitHub's default set; without it the preview namespace\n")
		b.WriteString("    # would leak after merge.\n")
		b.WriteString("    types: [opened, synchronize, reopened, closed]\n")
	}
	if staging {
		b.WriteString("  # Manual promotion to production.\n")
		b.WriteString("  workflow_dispatch:\n")
		b.WriteString("    inputs:\n")
		b.WriteString("      promote:\n")
		b.WriteString("        description: Promote the current staging release to production\n")
		b.WriteString("        type: boolean\n")
		b.WriteString("        default: false\n")
	}
	b.WriteString(`
concurrency:
  # One deploy per branch at a time; a newer push waits rather than cancelling
  # an in-flight rollout.
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  # buidl reads registry credentials from the standard Docker config, so
  # docker/login-action is all the auth setup required.
  BUILDKIT_HOST: ${{ vars.BUILDKIT_HOST }}

jobs:
`)
	if preview {
		b.WriteString(ciPreviewJob)
		b.WriteString(ciTeardownJob)
	}
	if staging {
		b.WriteString(ciStagingJob)
		b.WriteString(ciProductionJob)
	} else {
		b.WriteString(ciSingleJob)
	}
	return b.String()
}

const ciInstallBuidl = `      - name: Install buidl
        run: |
          curl -fsSL https://github.com/danecwalker/buidl/releases/latest/download/buidl-linux-amd64 -o /usr/local/bin/buidl
          chmod +x /usr/local/bin/buidl

      - name: Configure cluster access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
`

const ciLogin = `      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

`

const ciCheckout = `      - uses: actions/checkout@v5
        with:
          # buidl records the commit each release came from.
          fetch-depth: 0

`

const ciSingleJob = `  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
` + ciCheckout + ciLogin + ciInstallBuidl + `
      - name: Deploy
        run: buidl deploy --auto-rollback
`

const ciStagingJob = `  staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: staging
    steps:
` + ciCheckout + ciLogin + ciInstallBuidl + `
      - name: Deploy to staging
        run: buidl deploy -e staging --auto-rollback

`

const ciProductionJob = `  production:
    if: github.event_name == 'workflow_dispatch' && inputs.promote
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment:
      # Attach required reviewers to this GitHub environment to gate production.
      name: production
    steps:
` + ciCheckout + ciLogin + ciInstallBuidl + `
      - name: Promote staging to production
        # No rebuild: this deploys the exact digest that staging validated.
        run: buidl promote --from staging --to production --yes
`

const ciPreviewJob = `  preview:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
` + ciCheckout + ciLogin + ciInstallBuidl + `
      - name: Deploy preview
        id: deploy
        # The namespace and hostname derive from the PR number via BUIDL_SLUG,
        # so no per-branch configuration is needed.
        run: buidl deploy -e preview --auto-rollback

      - name: Comment the preview URL
        if: steps.deploy.outputs.url != ''
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            const release = '${{ steps.deploy.outputs.release }}';
            const body = ` + "`" + `Preview deployed: ${url}\n\nRelease: \` + "\\`" + `${release}\` + "\\`" + `` + "`" + `;
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo, issue_number: context.issue.number,
            });
            const existing = comments.find(c => c.body.startsWith('Preview deployed:'));
            if (existing) {
              await github.rest.issues.updateComment({ ...context.repo, comment_id: existing.id, body });
            } else {
              await github.rest.issues.createComment({ ...context.repo, issue_number: context.issue.number, body });
            }

`

const ciTeardownJob = `  teardown:
    # Fires on merge and on close-without-merge. Staging is a separate push
    # to main; coupling the two would leak previews on a failed staging
    # deploy and on PRs that never land.
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

` + ciInstallBuidl + `
      - name: Destroy preview
        # Same BUIDL_SLUG as the deploy job (pr-<n> from GITHUB_REF), so this
        # deletes the namespace that job created. --yes is required in CI.
        run: buidl destroy -e preview --yes

`

// githubWorkflow is the single-target pipeline. Tests compare against this shape.
var githubWorkflow = renderGithubWorkflow(false, false)
