package cli

// githubWorkflow is the starter CI pipeline written by `buidl init`.
//
// It encodes the workflow buidl is designed around:
//
//   - Pull requests get a preview environment and a plan, so a reviewer sees both
//     the running app and the infrastructure delta before merging.
//   - Closing a pull request tears the preview namespace down.
//   - Merges to main deploy to staging automatically.
//   - Production is a promotion of staging's exact digest, gated on a GitHub
//     environment approval — never a rebuild.
//
// It uses an in-cluster BuildKit so the runner needs no privileged container and
// no Docker daemon.
const githubWorkflow = `# Generated by ` + "`buidl init`" + `. Edit freely.
name: deploy

on:
  push:
    branches: [main]
  pull_request:
    # closed is not in GitHub's default set; without it the preview namespace
    # would leak after merge.
    types: [opened, synchronize, reopened, closed]
  # Manual promotion to production.
  workflow_dispatch:
    inputs:
      promote:
        description: Promote the current staging release to production
        type: boolean
        default: false

concurrency:
  # One deploy per branch at a time; a newer push supersedes an in-flight one.
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  # buidl reads registry credentials from the standard Docker config, so
  # docker/login-action is all the auth setup required.
  BUILDKIT_HOST: ${{ vars.BUILDKIT_HOST }}

jobs:
  # ---------------------------------------------------------------- preview ---
  preview:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          # buidl records the commit each release came from.
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buidl
        run: |
          curl -fsSL https://github.com/danecwalker/buidl/releases/latest/download/buidl-linux-amd64 -o /usr/local/bin/buidl
          chmod +x /usr/local/bin/buidl

      - name: Configure cluster access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Validate config
        run: buidl config validate

      - name: Deploy preview
        id: deploy
        # The namespace and hostname derive from the PR number via BUIDL_SLUG,
        # so no per-branch configuration is needed.
        run: buidl deploy -e preview --auto-rollback

      - name: Comment the preview URL
        if: steps.deploy.outputs.url != ''
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            const release = '${{ steps.deploy.outputs.release }}';
            const body = ` + "`" + `Preview deployed: ${url}\n\nRelease: \` + "\\`" + `${release}\` + "\\`" + `` + "`" + `;
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo, issue_number: context.issue.number,
            });
            const existing = comments.find(c => c.body.startsWith('Preview deployed:'));
            if (existing) {
              await github.rest.issues.updateComment({ ...context.repo, comment_id: existing.id, body });
            } else {
              await github.rest.issues.createComment({ ...context.repo, issue_number: context.issue.number, body });
            }

      - name: Plan production impact
        # Shows the reviewer what merging would change in production, without
        # touching it.
        run: buidl plan -e production --detailed

  # ------------------------------------------------------- preview teardown ---
  teardown:
    # Fires on merge and on close-without-merge. Staging is a separate push
    # to main; coupling the two would leak previews on a failed staging
    # deploy and on PRs that never land.
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install buidl
        run: |
          curl -fsSL https://github.com/danecwalker/buidl/releases/latest/download/buidl-linux-amd64 -o /usr/local/bin/buidl
          chmod +x /usr/local/bin/buidl

      - name: Configure cluster access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Destroy preview
        # Same BUIDL_SLUG as the deploy job (pr-<n> from GITHUB_REF), so this
        # deletes the namespace that job created. --yes is required in CI.
        run: buidl destroy -e preview --yes

  # ---------------------------------------------------------------- staging ---
  staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buidl
        run: |
          curl -fsSL https://github.com/danecwalker/buidl/releases/latest/download/buidl-linux-amd64 -o /usr/local/bin/buidl
          chmod +x /usr/local/bin/buidl

      - name: Configure cluster access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to staging
        run: buidl deploy -e staging --auto-rollback

  # ------------------------------------------------------------- production ---
  production:
    if: github.event_name == 'workflow_dispatch' && inputs.promote
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment:
      # Attach required reviewers to this GitHub environment to gate production.
      name: production
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buidl
        run: |
          curl -fsSL https://github.com/danecwalker/buidl/releases/latest/download/buidl-linux-amd64 -o /usr/local/bin/buidl
          chmod +x /usr/local/bin/buidl

      - name: Configure cluster access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Promote staging to production
        # No rebuild: this deploys the exact digest that staging validated.
        run: buidl promote --from staging --to production --yes
`
