package cli

// githubWorkflow is the optional pipeline written by `buidl init --ci`.
//
// The default product is one live app. This job deploys it on every push to
// main. Preview / staging / production jobs belong in a workflow the user
// writes after `buidl environment new`.
//
// It uses an in-cluster BuildKit so the runner needs no privileged container
// and no Docker daemon.
const githubWorkflow = `# Generated by ` + "`buidl init --ci`" + `. Edit freely.
name: deploy

on:
  push:
    branches: [main]

concurrency:
  # One deploy at a time; a newer push waits rather than cancelling an
  # in-flight rollout.
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  # buidl reads registry credentials from the standard Docker config, so
  # docker/login-action is all the auth setup required.
  BUILDKIT_HOST: ${{ vars.BUILDKIT_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          # buidl records the commit each release came from.
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install buidl
        run: |
          curl -fsSL https://github.com/danecwalker/buidl/releases/latest/download/buidl-linux-amd64 -o /usr/local/bin/buidl
          chmod +x /usr/local/bin/buidl

      - name: Configure cluster access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy
        run: buidl deploy --auto-rollback
`
