package project

import (
	"fmt"
	"strings"
)

// GenerateDockerfile renders a multi-stage Dockerfile for a detected project.
//
// Every template follows the same three rules, which matter more than the
// specific base images:
//
//  1. Dependency manifests are copied and installed before application source,
//     so a source-only change reuses the dependency layer.
//  2. The runtime stage carries no compiler or dev dependencies.
//  3. The process runs as a non-root user and honors $PORT.
//
// Returns an error for stacks with no template; callers should fall back to
// asking the user for a Dockerfile.
func GenerateDockerfile(d Detection) (string, error) {
	stack := d.Stack
	if stack == "" {
		stack = d.Kind
	}

	switch stack {
	case KindGo:
		return goDockerfile(d), nil
	case KindNode:
		return nodeDockerfile(d), nil
	case KindPython:
		return pythonDockerfile(d), nil
	case KindRuby:
		return rubyDockerfile(d), nil
	case KindRust:
		return rustDockerfile(d), nil
	case KindStatic:
		return staticDockerfile(d), nil
	default:
		return "", fmt.Errorf("no Dockerfile template for %s projects; write a Dockerfile and set build.dockerfile", stack)
	}
}

// header explains the file's provenance so nobody wonders whether it is
// hand-written or safe to edit.
func header() string {
	return `# Generated by ` + "`buidl init`" + `. Edit freely — buidl never regenerates this file.
# syntax=docker/dockerfile:1
`
}

func goDockerfile(d Detection) string {
	version := d.Runtime
	if version == "" {
		version = "1.25"
	}
	pkg := d.MainPackage
	if pkg == "" {
		pkg = "."
	}

	return header() + fmt.Sprintf(`
FROM golang:%s-alpine AS build
WORKDIR /src

# Dependencies first: this layer is reused until go.mod/go.sum change.
COPY go.mod go.sum* ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .
# CGO off yields a static binary that runs on a distroless/scratch base.
ENV CGO_ENABLED=0
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -trimpath -ldflags="-s -w" -o /out/app %s

# gcr.io/distroless/static carries no shell and no package manager, which is the
# smallest sane attack surface for a static Go binary.
FROM gcr.io/distroless/static-debian12:nonroot AS runtime
COPY --from=build /out/app /app
EXPOSE %d
ENV PORT=%d
# Numeric UID, not the name "nonroot": Kubernetes cannot verify a non-numeric
# user against runAsNonRoot and will refuse to start the container.
USER 65532:65532
ENTRYPOINT ["/app"]
`, version, pkg, d.Port, d.Port)
}

func nodeDockerfile(d Detection) string {
	version := d.Runtime
	if version == "" {
		version = "22"
	}

	// Vite/SPA projects produce static assets, so they get the nginx runtime
	// rather than a Node process.
	if d.Framework == "vite" {
		return staticNodeDockerfile(d, version)
	}

	install, installProd, lockfiles := nodeInstall(d.PackageManager)
	corepack := ""
	if d.PackageManager == PMPnpm || d.PackageManager == PMYarn {
		corepack = "RUN corepack enable\n"
	}

	build := ""
	if d.BuildCommand != "" {
		build = "RUN " + d.BuildCommand + "\n"
	}

	start := d.StartCommand
	if start == "" {
		start = "node index.js"
	}

	return header() + fmt.Sprintf(`
FROM node:%s-alpine AS deps
WORKDIR /app
%s
# Lockfile-only copy keeps the install layer cached across source changes.
COPY %s ./
RUN %s

FROM node:%s-alpine AS build
WORKDIR /app
%sCOPY --from=deps /app/node_modules ./node_modules
COPY . .
%s
FROM node:%s-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
%s
COPY --from=build /app .

# The build stage's node_modules includes dev dependencies. Replace it with a
# production-only tree; this must happen after the COPY, or the copy would
# overwrite it.
COPY %s ./
RUN rm -rf node_modules && %s && npm cache clean --force

EXPOSE %d
ENV PORT=%d
# The node image ships an unprivileged "node" user at uid 1000. Declared
# numerically because Kubernetes cannot verify a named user against runAsNonRoot.
USER 1000:1000
CMD %s
`, version, corepack, lockfiles, install,
		version, corepack, build,
		version, corepack, lockfiles, installProd,
		d.Port, d.Port, jsonArgs(start))
}

// staticNodeDockerfile builds SPA assets with Node, then serves them with nginx.
func staticNodeDockerfile(d Detection, version string) string {
	install, _, lockfiles := nodeInstall(d.PackageManager)
	corepack := ""
	if d.PackageManager == PMPnpm || d.PackageManager == PMYarn {
		corepack = "RUN corepack enable\n"
	}
	build := d.BuildCommand
	if build == "" {
		build = string(d.PackageManager) + " run build"
	}

	return header() + fmt.Sprintf(`
FROM node:%s-alpine AS build
WORKDIR /app
%sCOPY %s ./
RUN %s
COPY . .
RUN %s

FROM nginxinc/nginx-unprivileged:alpine AS runtime
# The unprivileged nginx image already runs as uid 101 and listens on 8080.
COPY --from=build /app/dist /usr/share/nginx/html
# SPA routing: unknown paths must fall through to index.html.
RUN printf 'server {\n  listen 8080;\n  root /usr/share/nginx/html;\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n  location /up { return 200 "ok"; }\n}\n' > /etc/nginx/conf.d/default.conf
EXPOSE 8080
# Stated numerically so Kubernetes can verify it against runAsNonRoot.
USER 101:101
`, version, corepack, lockfiles, install, build)
}

// nodeInstall returns the install command, the production-only install command,
// and the lockfile glob to copy for each package manager.
func nodeInstall(pm PackageManager) (install, installProd, lockfiles string) {
	switch pm {
	case PMPnpm:
		return "pnpm install --frozen-lockfile",
			"pnpm install --frozen-lockfile --prod",
			"package.json pnpm-lock.yaml"
	case PMYarn:
		return "yarn install --immutable",
			"yarn workspaces focus --production",
			"package.json yarn.lock"
	case PMBun:
		return "bun install --frozen-lockfile",
			"bun install --frozen-lockfile --production",
			"package.json bun.lock*"
	default:
		// `npm ci` requires a lockfile and is reproducible, unlike `npm install`.
		return "npm ci",
			"npm ci --omit=dev",
			"package.json package-lock.json"
	}
}

func pythonDockerfile(d Detection) string {
	version := d.Runtime
	if version == "" {
		version = "3.13"
	}

	var installStage, runtimeCopy string
	switch d.PackageManager {
	case PMUv:
		installStage = `COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-install-project`
		runtimeCopy = "COPY --from=build /app/.venv /app/.venv"
	case PMPoetry:
		installStage = `RUN pip install --no-cache-dir poetry poetry-plugin-export
COPY pyproject.toml poetry.lock ./
RUN poetry export --without-hashes --without dev -o requirements.txt \
    && python -m venv /app/.venv \
    && /app/.venv/bin/pip install --no-cache-dir -r requirements.txt`
		runtimeCopy = "COPY --from=build /app/.venv /app/.venv"
	default:
		installStage = `COPY requirements.txt ./
RUN python -m venv /app/.venv \
    && /app/.venv/bin/pip install --no-cache-dir -r requirements.txt`
		runtimeCopy = "COPY --from=build /app/.venv /app/.venv"
	}

	uvBin := ""
	if d.PackageManager == PMUv {
		uvBin = "COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv\n"
	}

	// Gunicorn/uvicorn are expected on PATH via the venv.
	start := d.StartCommand
	if start == "" {
		start = "python main.py"
	}

	collectStatic := ""
	if d.Framework == "django" {
		collectStatic = "# Bake static assets into the image so no shared volume is needed.\nRUN python manage.py collectstatic --noinput || true\n"
	}

	return header() + fmt.Sprintf(`
FROM python:%s-slim AS build
WORKDIR /app
%sENV PYTHONDONTWRITEBYTECODE=1 PIP_DISABLE_PIP_VERSION_CHECK=1
%s

COPY . .
%s
FROM python:%s-slim AS runtime
WORKDIR /app
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PATH="/app/.venv/bin:$PATH"

%s
COPY --from=build /app /app

# Run unprivileged: create the user in the runtime stage only.
RUN useradd --create-home --uid 10001 app && chown -R app:app /app
# Numeric UID, so runAsNonRoot can be verified.
USER 10001:10001

EXPOSE %d
ENV PORT=%d
CMD %s
`, version, uvBin, installStage, collectStatic, version, runtimeCopy, d.Port, d.Port, jsonArgs(start))
}

func rubyDockerfile(d Detection) string {
	version := d.Runtime
	if version == "" {
		version = "3.4"
	}

	assets := ""
	if d.Framework == "rails" {
		// SECRET_KEY_BASE_DUMMY lets asset precompilation run without the real
		// credential, so no secret is baked into a layer.
		assets = `# Precompile assets without needing real credentials at build time.
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
`
	}

	start := d.StartCommand
	if start == "" {
		start = "bundle exec rackup -o 0.0.0.0 -p 3000"
	}

	return header() + fmt.Sprintf(`
FROM ruby:%s-slim AS build
WORKDIR /app

# Build-only toolchain for native gem extensions; absent from the runtime image.
RUN apt-get update -qq && apt-get install --no-install-recommends -y \
    build-essential git libpq-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

ENV BUNDLE_DEPLOYMENT=1 BUNDLE_PATH=/usr/local/bundle BUNDLE_WITHOUT=development:test
COPY Gemfile Gemfile.lock ./
RUN bundle install \
    && rm -rf "${BUNDLE_PATH}"/ruby/*/cache

COPY . .
%s
FROM ruby:%s-slim AS runtime
WORKDIR /app

# Runtime libraries only — no compilers.
RUN apt-get update -qq && apt-get install --no-install-recommends -y \
    curl libpq5 postgresql-client \
    && rm -rf /var/lib/apt/lists/*

ENV RAILS_ENV=production RACK_ENV=production \
    BUNDLE_DEPLOYMENT=1 BUNDLE_PATH=/usr/local/bundle BUNDLE_WITHOUT=development:test \
    RAILS_LOG_TO_STDOUT=1 RAILS_SERVE_STATIC_FILES=1

COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /app /app

RUN useradd --create-home --uid 10001 app && chown -R app:app /app
# Numeric UID, so runAsNonRoot can be verified.
USER 10001:10001

EXPOSE %d
ENV PORT=%d
CMD %s
`, version, assets, version, d.Port, d.Port, jsonArgs(start))
}

func rustDockerfile(d Detection) string {
	version := d.Runtime
	if version == "" {
		version = "1"
	}
	bin := d.BinaryName
	if bin == "" {
		bin = "app"
	}

	return header() + fmt.Sprintf(`
FROM rust:%s-slim AS build
WORKDIR /src

# Build dependencies against a stub main so the dependency layer caches
# independently of application source.
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs \
    && cargo build --release --locked \
    && rm -rf src

COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    touch src/main.rs && cargo build --release --locked \
    && cp target/release/%s /out-app

FROM gcr.io/distroless/cc-debian12:nonroot AS runtime
COPY --from=build /out-app /app
EXPOSE %d
ENV PORT=%d
# Numeric UID, not the name "nonroot": Kubernetes cannot verify a non-numeric
# user against runAsNonRoot and will refuse to start the container.
USER 65532:65532
ENTRYPOINT ["/app"]
`, version, bin, d.Port, d.Port)
}

func staticDockerfile(d Detection) string {
	return header() + `
FROM nginxinc/nginx-unprivileged:alpine AS runtime
# This image runs as uid 101 and listens on 8080 without needing root.
COPY . /usr/share/nginx/html
RUN printf 'server {\n  listen 8080;\n  root /usr/share/nginx/html;\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n  location /up { return 200 "ok"; }\n}\n' > /etc/nginx/conf.d/default.conf
EXPOSE 8080
# Stated numerically so Kubernetes can verify it against runAsNonRoot.
USER 101:101
`
}

// jsonArgs renders a shell command as a JSON exec-form array.
//
// Exec form matters for correctness, not style: with shell form, the process
// runs as a child of /bin/sh, which does not forward SIGTERM. That breaks
// graceful shutdown and turns every rolling update into dropped connections.
func jsonArgs(cmd string) string {
	fields := strings.Fields(cmd)
	quoted := make([]string, 0, len(fields))
	for _, f := range fields {
		quoted = append(quoted, `"`+strings.ReplaceAll(f, `"`, `\"`)+`"`)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
